# Generated by Django 4.2.7 on 2025-07-19 16:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FleetOwner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('fleet_size', models.IntegerField(default=0)),
                ('business_type', models.CharField(max_length=100)),
                ('years_in_operation', models.PositiveIntegerField()),
                ('is_exclusive', models.BooleanField(default=False)),
                ('exclusive_until', models.DateTimeField(blank=True, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('total_rider_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('performance_bonus_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('locked_riders', models.BooleanField(default=False)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=100000, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
