# Generated by Django 4.2.7 on 2025-07-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='activation_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rider',
            name='last_activation_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='plate_number',
            field=models.CharField(blank=True, help_text='Tricycle plate number in format ABC123DD', max_length=8, null=True, unique=True),
        ),
    ]
