# fly.toml app configuration file generated for bold-sun-8647 on 2025-07-14T17:43:39+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bold-sun-8647'
primary_region = 'jnb'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[processes]
  app = 'gunicorn --bind :8000 --workers 4 --timeout 120 stika.wsgi'
  celery = 'celery -A stika worker --loglevel=INFO --concurrency=2'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/staticfiles'
  url_prefix = '/static/'

[[mounts]]
  source = 'stika_media'
  destination = '/app/media'
