# Generated by Django 4.2.7 on 2025-07-19 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riders', '0001_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignriderassignment',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riders.rider'),
        ),
        migrations.AddField(
            model_name='campaignreport',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignmetrics',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='agencies.agency'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='assigned_riders',
            field=models.ManyToManyField(related_name='campaigns', through='campaigns.CampaignRiderAssignment', to='riders.rider'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='agencies.agencyclient'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='campaignriderassignment',
            index=models.Index(fields=['campaign', 'status'], name='campaigns_c_campaig_9acb51_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignriderassignment',
            index=models.Index(fields=['rider', 'status'], name='campaigns_c_rider_i_de93a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignriderassignment',
            unique_together={('campaign', 'rider')},
        ),
        migrations.AlterUniqueTogether(
            name='campaignmetrics',
            unique_together={('campaign', 'date')},
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['agency', 'status'], name='campaigns_c_agency__960026_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date', 'end_date'], name='campaigns_c_start_d_996cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'created_at'], name='campaigns_c_status_6076a2_idx'),
        ),
    ]
