# Generated by Django 4.2.7 on 2025-07-26 15:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaign_agency_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(help_text='Contact person at pickup location', max_length=100)),
                ('contact_phone', models.CharField(help_text='Phone number for pickup coordination', max_length=20)),
                ('address', models.TextField(help_text='Full address of pickup location')),
                ('landmark', models.CharField(blank=True, help_text='Nearby landmark for easier location', max_length=255)),
                ('pickup_instructions', models.TextField(blank=True, help_text='Special instructions for sticker collection')),
                ('operating_hours', models.JSONField(default=dict, help_text="Operating hours for pickup (e.g., {'monday': '09:00-17:00', 'tuesday': '09:00-17:00'})")),
                ('is_active', models.BooleanField(default=True, help_text='Whether pickup location is currently available')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the pickup location')),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_locations', to='campaigns.campaigngeofence')),
            ],
            options={
                'ordering': ['geofence__priority'],
                'indexes': [models.Index(fields=['geofence'], name='campaigns_p_geofenc_ef76f9_idx'), models.Index(fields=['is_active'], name='campaigns_p_is_acti_a97fac_idx')],
            },
        ),
    ]
