# Generated by Django 4.2.7 on 2025-07-26 23:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_pickuplocation'),
        ('riders', '0002_rider_activated_at_rider_activation_attempts_and_more'),
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCooldown',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('random', 'Random Verification'), ('geofence_join', 'Geofence Join Verification'), ('manual', 'Manual Verification')], max_length=20)),
                ('last_attempt', models.DateTimeField()),
                ('cooldown_until', models.DateTimeField()),
                ('attempt_count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='attempted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='can_retry_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='geofence',
            field=models.ForeignKey(blank=True, help_text='Geofence being joined (for geofence_join type)', null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaigngeofence'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='verification_type',
            field=models.CharField(choices=[('random', 'Random Verification'), ('geofence_join', 'Geofence Join Verification'), ('manual', 'Manual Verification')], default='random', help_text='Type of verification request', max_length=20),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['rider', 'verification_type', 'attempted_at'], name='verificatio_rider_i_184dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['can_retry_after'], name='verificatio_can_ret_640831_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['geofence', 'status'], name='verificatio_geofenc_094fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['verification_type', 'status'], name='verificatio_verific_88e81f_idx'),
        ),
        migrations.AddField(
            model_name='verificationcooldown',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riders.rider'),
        ),
        migrations.AddIndex(
            model_name='verificationcooldown',
            index=models.Index(fields=['rider', 'verification_type'], name='verificatio_rider_i_9975e6_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcooldown',
            index=models.Index(fields=['cooldown_until'], name='verificatio_cooldow_9b0ebe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='verificationcooldown',
            unique_together={('rider', 'verification_type')},
        ),
    ]
