# Generated by Django 4.2.7 on 2025-07-19 16:40

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('subdomain', models.CharField(max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Subdomain must be lowercase alphanumeric with optional hyphens', regex='^[a-z0-9]([a-z0-9-]*[a-z0-9])?$')])),
                ('agency_type', models.CharField(choices=[('digital', 'Digital Agency'), ('traditional', 'Traditional Agency'), ('full_service', 'Full Service Agency'), ('boutique', 'Boutique Agency'), ('in_house', 'In-House Team')], max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('subscription_tier', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], default='starter', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('api_rate_limit', models.IntegerField(default=1000)),
                ('max_campaigns', models.IntegerField(default=50)),
                ('monthly_spend_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agency_logos/')),
                ('primary_color', models.CharField(default='#1976d2', max_length=7)),
                ('secondary_color', models.CharField(default='#dc004e', max_length=7)),
                ('custom_domain', models.CharField(blank=True, max_length=255)),
                ('api_enabled', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=7.5, max_digits=5)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_campaigns', models.IntegerField(default=0)),
                ('exclusive_zones', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('locked_in_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitiveIntelligence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_patterns', models.JSONField(default=dict)),
                ('campaign_patterns', models.JSONField(default=dict)),
                ('rider_patterns', models.JSONField(default=dict)),
                ('pricing_patterns', models.JSONField(default=dict)),
                ('analysis_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='ExclusiveContract',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_type', models.CharField(choices=[('fleet', 'Fleet Owner'), ('agency', 'Agency'), ('advertiser', 'Advertiser')], max_length=20)),
                ('partner_id', models.UUIDField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('exclusivity_radius', models.IntegerField(help_text='Kilometers')),
                ('auto_renew', models.BooleanField(default=False)),
                ('early_termination_penalty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guaranteed_minimum_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volume_bonuses', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=50)),
                ('changes', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgencySettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('webhook_notifications', models.BooleanField(default=False)),
                ('default_campaign_duration', models.PositiveIntegerField(default=30)),
                ('auto_approve_campaigns', models.BooleanField(default=False)),
                ('require_client_approval', models.BooleanField(default=True)),
                ('report_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('include_rider_details', models.BooleanField(default=False)),
                ('white_label_reports', models.BooleanField(default=True)),
                ('auto_payment_threshold', models.DecimalField(decimal_places=2, default=1000, max_digits=12)),
                ('payment_terms', models.PositiveIntegerField(default=7)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='agencies.agency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgencyClient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('client_type', models.CharField(choices=[('sme', 'Small/Medium Enterprise'), ('corporate', 'Corporate'), ('nonprofit', 'Non-Profit'), ('government', 'Government'), ('startup', 'Startup')], max_length=20)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('industry', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('average_campaign_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_platform_access', models.BooleanField(default=False)),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preferred_locations', models.JSONField(default=list)),
                ('brand_guidelines', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='agencies.agency')),
                ('view_only_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyAPIKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('permissions', models.JSONField(default=dict)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='agencies.agency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['subdomain'], name='agencies_ag_subdoma_de7d27_idx'),
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['subscription_tier', 'created_at'], name='agencies_ag_subscri_fbef9e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='agencies_au_user_id_277c77_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model', 'object_id'], name='agencies_au_model_c5f189_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agencyclient',
            unique_together={('agency', 'slug')},
        ),
    ]
